services:
  - type: web
    name: hotel-aurora-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python seed_rooms.py && gunicorn run_server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hotel-aurora-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PASSWORD_RESET_TOKEN_MAX_AGE
        value: 1800

databases:
  - name: hotel-aurora-db
    plan: free

